const VERSION='quran-memorizer-pwa-v3';
const SHELL=VERSION+'-shell',RUNTIME=VERSION+'-runtime';
const APP_SHELL=['./','./index.html','./reader.html','./app.css','./home.js','./surahs.js','./manifest.webmanifest','./icons/icon-192.png','./icons/icon-512.png','./icons/maskable-512.png'];
self.addEventListener('install',e=>e.waitUntil(caches.open(SHELL).then(c=>c.addAll(APP_SHELL)).then(()=>self.skipWaiting())));
self.addEventListener('activate',e=>e.waitUntil((async()=>{for(const k of await caches.keys())if(![SHELL,RUNTIME].includes(k))await caches.delete(k);await self.clients.claim();})()));
function isQuranResource(u){return u.hostname==='api.quran.com'||u.hostname==='verses.quran.foundation';}
self.addEventListener('fetch',e=>{if(e.request.method!=='GET')return;const u=new URL(e.request.url);if(isQuranResource(u)){e.respondWith((async()=>{const c=await caches.open(RUNTIME),h=await c.match(e.request);if(h)return h;const r=await fetch(e.request);if(r&&(r.ok||r.type==='opaque'))await c.put(e.request,r.clone());return r;})());return;}if(u.origin===self.location.origin){e.respondWith((async()=>{const h=await caches.match(e.request,{ignoreSearch:e.request.mode==='navigate'});if(h)return h;try{const r=await fetch(e.request),c=await caches.open(SHELL);if(r.ok)await c.put(e.request,r.clone());return r;}catch(err){if(e.request.mode==='navigate')return await caches.match('./index.html');throw err;}})());}});
async function cacheOne(c,u){const req=new Request(u,{mode:'cors'}),h=await c.match(req);if(h)return;const r=await fetch(req);if(!r||!(r.ok||r.type==='opaque'))throw new Error('bad response');await c.put(req,r.clone());}
self.addEventListener('message',e=>{const d=e.data||{};if(d.type!=='CACHE_URLS'||!Array.isArray(d.urls))return;e.waitUntil((async()=>{const c=await caches.open(RUNTIME);let done=0,hadError=false,next=0;const total=d.urls.length,concurrency=4;async function worker(){while(true){const i=next++;if(i>=total)return;try{await cacheOne(c,d.urls[i]);}catch(err){hadError=true;}done++;e.source?.postMessage({type:'CACHE_PROGRESS',id:d.id,done,total});}}await Promise.all(Array.from({length:concurrency},worker));e.source?.postMessage({type:hadError?'CACHE_ERROR':'CACHE_DONE',id:d.id,done,total});})());});
